# Dockerfile for Nginx
FROM nginx:latest

# Copy the default Nginx configuration for Symfony
COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf

# Expose port 80 for HTTP
EXPOSE 80
